### ISSUE TITLE
[FEAT] Exception 관련 공통 클래스 작성 및 구현

### ISSUE THREAD

**Issue by HunSeongPark** [approval-please/approval-please-Spring#1]
## 🔥 Feature Issue
Exception 관련 공통 클래스 작성 및 구현

## ✅ TODO
 - [x] CustomErrorType 클래스 추가
 - [x] CustomException 클래스 추가
 - [x] CustomExceptionHandler 클래스 추가
 - [x] ErrorResponse 클래스 추가
