### ISSUE TITLE
[FEAT] 결재서류 승진포인트 적립 기능 추가

### ISSUE THREAD

**Issue by eujjong18** [approval-please/approval-please-Spring#115]
## 🔥 Feature Issue
결재서류와 관련된 승진포인트 적립 기능 추가

## ✅ TODO
 - [x] 결재서류 승진포인트 적립 기능 추가
 - [x] 상세조회, 목록조회(전체/관심) response에 documentId 추가
 - [x] 상세조회 response에 isModified(게시글 수정 유무) 추가
