### ISSUE TITLE
[FEAT] 댓글, 좋아요 목록 조회 Request Body -> Request Parameter 변경

### ISSUE THREAD

**Issue by HunSeongPark** [approval-please/approval-please-Spring#138]
## 🔥 Feature Issue
댓글, 좋아요 목록 조회 Request Body -> Request Parameter 변경
cause : POST 메서드에 대해 Request Body 불가능

## ✅ TODO
 - [x] 댓글 목록조회 Request Body -> Request Parameter 변경
 - [x] 댓글 목록조회 isModified 추가
 - [x] 좋아요 목록조회 Request Body -> Request Parameter 변경
 - [x] 테스트코드 수정
