### ISSUE TITLE
[FEAT] 일반 / SNS 회원가입 완료 시 JWT Token 리턴하도록 변경

### ISSUE THREAD

**Issue by HunSeongPark** [approval-please/approval-please-Spring#140]
## 🔥 Feature Issue
일반 / SNS 회원가입 완료 시 JWT Token 리턴하도록 변경
cause : 회원가입 시 바로 로그인 처리를 위함

## ✅ TODO
 - [x] SNS 회원가입 시, SNS에서 받아온 이메일 정보로 회원가입 처리
 - [x] 일반 회원가입 완료 시 JWT Token 리턴 변경
 - [x] SNS 회원가입 완료 시 JWT Token 리턴 변경
