### ISSUE TITLE
[FEAT] 결재서류 수정사항 반영

### ISSUE THREAD

**Issue by eujjong18** [approval-please/approval-please-Spring#151]
## 🔥 Feature Issue
결재서류 수정사항 반영

## ✅ TODO
 - [x] 상세 조회 - 스크랩, 좋아요 유무 응답 추가
 - [x] 상세 조회 - 결재보고서 작성 유무 응답 추가
 - [ ] 목록 조회 - 상태별 필터링 추가
 - [ ] 목록 조회 - 최신순/인기순/결재순 필터링 추가
