### ISSUE TITLE
[FEAT] 관심부서 설정/조회 기능 구현

### ISSUE THREAD

**Issue by sharpie1330** [approval-please/approval-please-Spring#153]
## 🔥 Feature Issue
관심부서 설정/조회 기능을 구현합니다.

## ✅ TODO
 - [x] 사용자가 정한 순서대로 정렬된 관심부서 목록 저장
 - [x] 사용자가 정한 순서대로 저장했던 관심부서 목록 조회
 - [x] 해당 사용자 존재 여부 확인
 - [x] 올바른 요청인지 확인
