### ISSUE TITLE
[FEAT] 결재서류 상세조회 수정사항 반영

### ISSUE THREAD

**Issue by eujjong18** [approval-please/approval-please-Spring#155]
## 🔥 Feature Issue
결재서류 상세조회 수정사항 반영

## ✅ TODO
 - [x] 상세조회 response userId 추가
 - [x] 상세조회 response isVoted 추가
 - [x] 상세조회 response reportId 추가
 - [x] DTO 검토
