### ISSUE TITLE
[FEAT] 관심부서 관련 엔티티 수정 및 타입 추가

### ISSUE THREAD

**Issue by HunSeongPark** [approval-please/approval-please-Spring#17]
## 🔥 Feature Issue
관심부서 관련 엔티티 수정 및 타입 추가

## ✅ TODO
 - [x] Category -> LikeCategory로 테이블명 수정
 - [x] LikeCategory 엔티티 구성
 - [x] CategoryType 추가
 - [x] Category 연관관계 Enum 값으로 변경
