### ISSUE TITLE
[FEAT] 결재서류 로직 수정 & 상세조회 알람여부 추가

### ISSUE THREAD

**Issue by eujjong18** [approval-please/approval-please-Spring#171]
## 🔥 Feature Issue
결재서류 로직 수정

## ✅ TODO
 - [x] 상세조회 response에 notification 추가
 - [x] 상세조회 댓글 수 로직 수정
 - [x] 상세조회 좋아요/스크랩 로직 수정
 - [x] 삭제 로직 수정
