### ISSUE TITLE
[REFACTOR] ReportService 코드 가독성 향상

### ISSUE THREAD

**Issue by sharpie1330** [approval-please/approval-please-Spring#199]
## 🔥 Feature Issue
메소드 추출, 변수명 변경, 변수 재할당 지양, 변수 인라인 (Inline Variable), Optional 사용 시 NoSuchElementException 방지 리팩토링을 진행한다. 
정렬조건(sortBy)을 숫자로 구분하지 않고 별도의 enum type으로 정의해 코드 이해를 용이하게 한다.
또한 불필요한 코드를 삭제하고 재정렬해 변경하며, 설명 주석을 추가한다.

## ✅ TODO
 - [x] 직관적인 이름으로 메소드 추출
 - [x] 변수명 의미가 더 잘 전달되도록 변경
 - [x] 변수 재할당 코드 수정
 - [x] 변수 인라인(Inline Variable)
 - [x] Optional 타입에 대해 get() 대신 ifPresent() 및 orElseThrow() 사용해 NoSuchElementException 방지
 - [x] ReportSortType enum 클래스 생성, 사용
 - [x] 불필요한 코드 삭제
 - [x] 논리에 맞게 진행되도록 코드 재정렬
 - [x] 설명 주석 추가
 - [x] == 대신 eqauls()로 값 비교하도록 코드 수정
