### ISSUE TITLE
[FEAT] 결재하기 게시글 삭제 기능 구현

### ISSUE THREAD

**Issue by eujjong18** [approval-please/approval-please-Spring#21]
## 🔥 Feature Issue
'결재하기'에서 결재서류 삭제 기능 구현

## ✅ TODO
 - [x] 게시글 삭제 쿼리 작성(Document, Image, Tag, Link)
 - [x] 게시글 삭제 권한 체크
 - [x] 해당하는 게시글이 없을 경우 예외처리
