### ISSUE TITLE
[FEAT] 일반 회원가입 기능 구현

### ISSUE THREAD

**Issue by sharpie1330** [approval-please/approval-please-Spring#6]
## 🔥 Feature Issue
이메일로 회원가입(일반 사용자)하는 기능 구현

## ✅ TODO
 - [x] 일반 사용자 등록 쿼리 작성
 - [x] 같은 이메일, 휴대전화번호로 가입한 이력 존재 시 예외처리
 - [ ] 테스트 코드 작성

**Comment by sharpie1330** [comment]
다른 로그인/회원가입 관련 건에 대해서도 브랜치 나누어 작업해야할 것 같아 담당:샤피로 변경합니다.

**Comment by sharpie1330** [comment]
이메일 중복 예외처리의 경우 로그인 단에서 처리하므로 항목 삭제합니다
