### ISSUE TITLE
[FEAT] 마이페이지 - 커뮤니티 (결재톡톡, 결재보고서) 조회 + 댓글 / 스크랩 조회 (유형별 : 결재서류, 결재톡톡, 결재보고서)

### ISSUE THREAD

**Issue by Huh21** [approval-please/approval-please-Spring#85]
## 🔥 Feature Issue
[FEAT] 마이페이지 - 커뮤니티 (결재톡톡, 결재보고서) 조회 + 댓글 / 스크랩 조회 (유형별 : 결재서류, 결재톡톡, 결재보고서)

## ✅ TODO
 - [ ] 결재톡톡 조회
 - [ ] 결재보고서 조회
 - [ ] 댓글 목록 조회 (결재서류, 결재톡톡, 결재보고서)
 - [ ] 스크랩 목록 조회 (결재서류, 결재톡톡, 결재보고서)
 - [ ] 유형별(결재서류, 결재톡톡, 결재보고서) 조회 처리
